--- # Jenkins Main Playbook

- hosts: localhost
  connection: local
  become: yes

  vars:
    JAVA_HOME: /opt/app/home/java

  environment:
    JAVA_HOME: "{{ JAVA_HOME }}"
  tasks:

  - name: execute PreSetup Playbook
    include_tasks: preSetup.yml

  - name: execute installJava.yml
    include_tasks: installJava.yml
    tags: installJava

  - name: execute installJenkins Playbook
    include_tasks: installJenkins.yml
    tags: installjenkins

  handlers:

    - name: restart docker
      service:
        name: docker
        state: restarted
